---
- name: install lamp stack on ubuntu
  hosts: all
  become: yes
  vars:
    php_package_name: php
    lib_package_name: libapache2-mod-php
    phpmysql_package_name: php-mysql
  tasks: 
    - name: install apache2
      package:
        name: "{{ apache_package_name }}"
        state: present
      when: ansible_facts['distribution'] == "ubuntu"  
      notify: 
        - enable and start service
    - name: install php
      apt:
        name: 
          - "{{ php_package_name }}"
          - "{{ lib_package_name }}"
          - "{{ phpmysql_package_name }}"
        state: present
      when: ansible_facts['distribution'] == "ubuntu"
    - name: install httpd
      package:
        name: "{{ apache_package_name }}"
        state: present
      when: ansible_facts['distribution'] == "centos"  
      notify: 
        - enable and start service
    - name: install php
      yum:
        name: 
          - "{{ php_package_name }}"
          - "{{ phpmysql_package_name }}"
        state: present
      when: ansible_facts['distribution'] == "centos"
    - name: create a file with content
      copy:
        src: info.php
        dest: /var/www/html/info.php
      notify: restart service
           
  handlers:
    - name: enable and start service
      package:
        name: "{{ service_name }}" 
        enabled: yes
        state: started
    - name: restart service
      package:
        name: "{{ service_name }}" 
        state: restarted