---
- name: install lamp stack on ubuntu
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php
      ansible.builtin.apt:
        name: php libapache2-mod-php php-mysql
        state: present
    
    
