---
- name: installing wildfly on ubuntu 20.04
  hosts: all
  become: yes
  tasks:
  - name: install java
    apt:
      name: openjdk-11-jdk
      update_cache: yes
      state: present
  - name: create a wildfly group
    group:
      name: wildfly
      system: yes
      state: present
  - name: create a wildfly user
    user:
      name: wildfly
      create_home: yes
      group: wildfly
      system: yes
      home: /opt/wildfly      
      shell: /sbin/nologin
      state: present
  - name: create directory
    file:
      name: /tmp
      state: directory
  - name: extract wildfly 27.0.1
    unarchive:
      src: https://github.com/wildfly/wildfly/releases/download/27.0.1.Final/wildfly-27.0.1.Final.tar.gz
      dest: /tmp
      remote_src: yes
  - name: copy tar file to folder
    copy:
      src: /tmp/wildfly-27.0.1.Final/
      dest: /opt/wildfly
      remote_src: yes
  - name: change permissions
    file:
      dest: /opt/wildfly
      recurse: yes
      owner: wildfly
      group: wildfly
      state: directory
  - name: make directory
    file:
      name: /etc/wildfly
      state: directory
  - name: copy config files
    copy:
      src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
      dest: /etc/wildfly
      remote_src: yes
  - name: copy launch file
    copy:
      src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
      dest: /opt/wildfly/bin
      remote_src: yes
  - name: add executable permissions for shell files
    command: sudo sh -c 'chmod +x /opt/wildfly/bin/*.sh'
  - name: copy systemd unit file
    copy:
      src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
      dest: /etc/systemd/system/
      remote_src: yes
  - name: daemon reload and start wildfly
    systemd:
      name: wildfly
      daemon_reload: yes
      enabled: yes
      state: started
  - name: copy mgmt user files to dest1
    copy:
      src: /home/devops/mgmt-users.properties/
      dest: /opt/wildfly/standalone/configuration/mgmt-users.properties
  - name: copy mgmt user files to dest2
    copy:
      src: /home/devops/mgmt-users.properties/
      dest: /opt/wildfly/domain/configuration/mgmt-users.properties
  - name: copy mgmt user files to dest1
    copy:
      src: /home/devops/mgmt-group.properties/
      dest: /opt/wildfly/standalone/configuration/mgmt-groups.properties
  - name: copy mgmt group files to dest2
    copy:
      src: /home/devops/mgmt-group.properties/
      dest: /opt/wildfly/domain/configuration/mgmt-users.properties
  - name: copy console config file to dest
    copy:
      src: /home/devops/wildfly.conf/
      dest: /etc/wildfly/wildfly.conf
  - name: copy console launch file to dest
    copy:
      src: /home/devops/lauch.sh/
      dest: /opt/wildfly/bin/launch.sh
  - name: wildfly restart
    systemd:
      name: wildfly
      state: restarted
  - name: copy console service file to dest
    copy:
      src: /home/devops/wildfly.service/
      dest: /etc/systemd/system/wildfly.service
  - name: make console run directory
    file:
      name: /var/run/wildfly/
      state: directory
  - name: change permissions to console dir
    file:
      dest: /var/run/wildfly/
      recurse: yes
      owner: wildfly
      group: wildfly
      state: directory
  - name: restart wildfly.service
    systemd:
      name: wildfly
      daemon_reload: yes
      state: restarted