---
- name: installing OpenMRS on ubuntu 20.04
  hosts: all
  become: yes
  tasks:
  - name: install java 8
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
  - name: create a tomcat group
    group:
      name: tomcat
      system: yes
      state: present
  - name: create a wildfly user
    user:
      name: tomcat
      create_home: yes
      group: tomcat
      system: yes
      home: /opt/tomcat      
      shell: /bin/nologin
      state: present
  - name: extract tomcat 7
    unarchive:
      src: https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.109/bin/apache-tomcat-7.0.109.tar.gz
      dest: /tmp
      remote_src: yes
  - name: copy tar file to folder
    copy:
      src: /tmp/apache-tomcat-7.0.109/
      dest: /opt/wildfly
      remote_src: yes
  - name: change home dir permissions
    file:
      dest: /opt/tomcat
      recurse: yes
      owner: tomcat
      group: tomcat
      state: directory
  - name: change conf file permissions 
    file:
      path: conf
      recurse: yes
      group: tomcat
      mode: g+r,g+x
  - name: change permissions for webapps work temp logs folders
    file:
      path: 
        - webapps/
        - work/
        - temp/
        - logs/
      recurse: yes
      owner: tomcat
      group: tomcat
  - name: copy tomcat.service file
    copy:
      src: ~/Ansible/Playbooks/openmrs/tomcat.service
      dest: /etc/systemd/system/tomcat.service
      owner: tomcat
      group: tomcat
  - name: service reload and enable
    systemd: 
      name: tomcat
      daemon_reload: yes
      enabled: yes
      state: started
  - name: create a openmrs dir
    file:
      path: /var/lib/OpenMRS
      state: directory
  - name: openmrs file permissions
    file:
      path: /var/lib/OpenMRS
      owner: tomcat
      group: tomcat
  - name: download openmrs war file
    get_url:
      url: https://sourceforge.net/projects/openmrs/files/releases/OpenMRS_Platform_2.5.0/openmrs.war
      dest: /opt/tomcat/webapps/
  - name: file permission for openmrs
    file:
      path: /opt/tomcat/webapps/openmrs.war
      owner: tomcat
      group: tomcat 
  