---
- name: Finding out what can be done if module not found
  gather_facts: no
  hosts: all
  tasks:
    - name: executing linux command directly
      become: yes
      command:
        cmd: 'ufw app list'
      register: ufw_output
    - name: print the output
      debug:
        msg: "{{ ufw_output }}"
    - name: using ansible magic variable playbook_dir
      debug:
        msg: "This playbook is executed from {{ playbook_dir }} and the python used by ansible is over here {{ ansible_playbook_python }}"