---
- hosts: appservers
  become: yes
  vars:
    xmx_size: 512
    perm_size: 256
    tomcat_user: devops
    tomcat_password: devops
    tomcat_packages:
      - tomcat8-docs
      - tomcat8-admin
      - tomcat8-examples
  tasks:
    - name: Update ubuntu packages and install tomcat8
      apt:
        name: tomcat8
        update_cache: yes
        state: present
    - name: copy tomcat8 
      template:
        src: tomcat8.j2
        dest: /etc/default/tomcat8
      notify:
        - restart and enable tomcat
    - name: install tomcat packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ tomcat_packages }}"
    - name: copy tomcat users
      template:
        src: tomcat-users.xml.j2
        dest: /etc/tomcat8/tomcat-users.xml
      notify:
        - restart and enable tomcat
  handlers:
    - name: restart and enable tomcat
      service:
        name: tomcat8
        enabled: yes
        state: restarted