---
# handlers file for skeleton
- name: restart tomcat
  ansible.builtin.systemd:
    name: "{{ tomcat_service_name }}"
    state: restarted
- name: enable and reload tomcat
  ansible.builtin.systemd:
    name: "{{ tomcat_service_name }}"
    daemon_reload: yes
    enabled: yes
    state: restarted
- name: add execute permissions to shell files
  ansible.builtin.command: "sudo sh -c 'chmod +x {{ user_home }}/bin/*.sh'"
