---
- hosts: webserver
  become: yes
  tasks:
  - name: fail for other platforms
    fail:
      msg: "This playbook is developed only for RHEL platforms"
    when:
    - ansible_os_family != "RedHat"
  - debug:
      msg: "Starting the installation"
  - name: install httpd
    yum:
      name: httpd
      state: present
    notify:
    - restart httpd
  - debug:
      msg: "Installed Httpd"
  - name: install php modules
    yum:
      name: "{{ item }}"
      state: present
    loop:
    - php
    - php-mysql
    - php-pdo 
  - name: copy php page
    copy:
      src: info.php
      dest: /var/www/html/info.php
    notify:
    - restart httpd
  handlers:
  - name: restart httpd
    service: 
      name: httpd
      enabled: yes
      state: restarted
# inspired from https://www.tecmint.com/install-lamp-in-centos-7/