---
- hosts: all
  become: yes
  vars:
    java_path: /usr/lib/jvm/java-1.8.0-openjdk-amd64
  tasks:
    - name:  Create file
      template:
        src: readme.txt.j2
        dest: /home/ansible/readme.txt

    - name: Dummy Configuration
      template:
        src: tomcat.service.j2
        dest: /home/ansible/tomcat.service