---
- name: installation and config mongo db
  hosts: all
  become: yes
  tasks:
    - name: add apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present
    - name: add repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
        state: present
        filename: mongodb-org-5.0
    - name: install mongo db
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
      notify: 
        - start mongodb
    - name: copy config file
      copy:
        src: mongodb.conf
        dest: /etc/mongodb.conf
      notify:
        - restart mongod service
  handlers:
    - name: start mongodb
      systemd:
        name: mongod
        state: started
        enable: yes
    - name: restart mongod service
      systemd:
        name: mongod
        state: restarted

