---
- name: installation and config mongo db
  hosts: all
  become: yes
  vars:
    package: mongodb-org
    version: "6.0"
  tasks:
    - name: add apt key
      apt_key:
        url: "https://www.mongodb.org/static/pgp/server-{{ version }}.asc"
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add repo
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ version }} multiverse"
        state: present
        filename: "mongodb-org-{{ version }}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: add repo centos
      yum_repository:
        name: "mongodb-org-{{ version }}"
        description: "mongodb-org-{{ version }}"
        baseurl: "https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{ version }}/x86_64/"
        gpgcheck: 1
        enabled: 1
        gpgkey: "https://www.mongodb.org/static/pgp/server-{{ version }}.asc"
      when: ansible_facts['distribution'] == "CentOS"
    - name: install mongo db
      package:
        name: "{{ package }}"
        state: present
      notify:
        - start mongodb
    - name: copy config file
      copy:
        src: mongodb.conf
        dest: /etc/mongodb.conf
      notify:
        - restart mongod service
  handlers:
    - name: start mongodb
      systemd:
        name: mongod
        state: started
        enabled: yes
    - name: restart mongod service
      systemd:
        name: mongod
        state: restarted