---
- name: installation and config mongo db
  hosts: all
  become: yes
  vars:
    package: mongodb-org
  tasks:
    - name: add apt key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present
      when: ansible_facts['distribution'] == "ubuntu"
    - name: add repo
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
        state: present
        filename: mongodb-org-5.0
      when: ansible_facts['distribution'] == "ubuntu" 
    - name: add repo centos
      copy:
        src: mongodb-org.repo
        dest: /etc/yum.repos.d/mongodb-org-6.0.repo
      when: ansible_facts['distribution'] == "centos"  
    - name: install mongo db
      package:
        name: "{{ package }}"
        state: present
      notify: 
        - start mongodb
    - name: copy config file
      copy:
        src: mongodb.conf
        dest: /etc/mongodb.conf
      notify:
        - restart mongod service
  handlers:
    - name: start mongodb
      systemd:
        name: mongod
        state: started
        enable: yes
    - name: restart mongod service
      systemd:
        name: mongod
        state: restarted

