---
- name: learning template expressions
  hosts: all
  tasks:
    - name: default value for undefined variable
      debug: 
        msg: "{{ username | default('admin')}}"
    - name: default value while looking up for environment variables
      debug:
        msg: "{{ lookup('env', 'MY_APP') | default('qthrms', true)}}"