---
- name: java installation for multi version
  hosts: all
  become: yes
  vars:
    version: "13"
  tasks:
    - name: java installation
      apt:
        name: "openjdk-{{ version }}-jdk"
        update_cache: yes
        state: present
