---
- hosts: all
  become: yes
  tasks:
  - name: install git
    apt:
      name: git
      update_cache: yes
      state: present
      


# install git 
# the machines are ubuntu
# sudo apt update
# sudo apt-get install git 
