---
- name: installation and config nopcommerce application
  hosts: all
  become: yes
  tasks:
    - name: install MS keys and packages
      apt:
        deb: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
    - name:
      apt:
        name:
          - apt-transport-https
          - aspnetcore-runtime-7.0
        update_cache: yes
        state: present
          
    
      
