---
# tasks file for role_skeleton
- name: Fail the execution when the distribution is not ubuntu and centos
  fail:
    msg: "This playbook will work only on ubuntu instances. Support for other OS will be added soon"
  when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution'] != "CentOS"
- name: install apache
  package:
    name: "{{ apache_package }}"
    state: present
  notify:
    - log installed apache server
- name: install php packages
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ php_packages }}"
- name: copy the php info page
  copy:
    dest: "{{ info_page_path }}"
    src: "info.php"
  notify:
    - log info page is copied
    - restart apache
- name: ensure the service is running
  service:
    name: "{{ apache_package }}"
    enabled: yes
    state: started
